// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./components/todos/AddTodo.vue')['default']
    Alert: typeof import('./components/Alert/Alert.vue')['default']
    AntDesignMessageFilled: typeof import('~icons/ant-design/message-filled')['default']
    BiPlusLg: typeof import('~icons/bi/plus-lg')['default']
    BiXLg: typeof import('~icons/bi/x-lg')['default']
    CarbonAddAlt: typeof import('~icons/carbon/add-alt')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonCheckbox: typeof import('~icons/carbon/checkbox')['default']
    CarbonCheckboxChecked: typeof import('~icons/carbon/checkbox-checked')['default']
    CarbonEdit: typeof import('~icons/carbon/edit')['default']
    CarbonEmail: typeof import('~icons/carbon/email')['default']
    CarbonGroupAccount: typeof import('~icons/carbon/group-account')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogin: typeof import('~icons/carbon/login')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogout: typeof import('~icons/carbon/logout')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPassword: typeof import('~icons/carbon/password')['default']
    CarbonPenFountain: typeof import('~icons/carbon/pen-fountain')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    CarbonUpload: typeof import('~icons/carbon/upload')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CreateNewMessage: typeof import('./components/Messages/message/CreateNewMessage.vue')['default']
    EvaQuestionMarkCircleFill: typeof import('~icons/eva/question-mark-circle-fill')['default']
    Message: typeof import('./components/Messages/message/Message.vue')['default']
    MessageBoard: typeof import('./components/Messages/MessageBoard.vue')['default']
    NavBarGuest: typeof import('./components/NavBarGuest.vue')['default']
    NavBarUser: typeof import('./components/NavBarUser.vue')['default']
    NewList: typeof import('./components/todos/NewList.vue')['default']
    OcticonChecklist16: typeof import('~icons/octicon/checklist16')['default']
    README: typeof import('./components/README.md')['default']
    TodoList: typeof import('./components/todos/TodoList.vue')['default']
    UpdateMessage: typeof import('./components/Messages/message/UpdateMessage.vue')['default']
  }
}

export { }
