// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./components/todos/AddTodo.vue')['default']
    Alert: typeof import('./components/Alert/Alert.vue')['default']
    CarbonEmail: typeof import('~icons/carbon/email')['default']
    CarbonPassword: typeof import('~icons/carbon/password')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CreateNewMessage: typeof import('./components/Messages/message/CreateNewMessage.vue')['default']
    Message: typeof import('./components/Messages/message/Message.vue')['default']
    MessageBoard: typeof import('./components/Messages/MessageBoard.vue')['default']
    NavBarGuest: typeof import('./components/NavBarGuest.vue')['default']
    NavBarUser: typeof import('./components/NavBarUser.vue')['default']
    NewList: typeof import('./components/todos/NewList.vue')['default']
    README: typeof import('./components/README.md')['default']
    TodoList: typeof import('./components/todos/TodoList.vue')['default']
    UpdateMessage: typeof import('./components/Messages/message/UpdateMessage.vue')['default']
  }
}

export { }
